### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by ghost** [SleepyBandit/oxford-dictionary#2]
I am using this on my localhost, I am getting 'Authentication parameters missing' as a response. Is it a problem with my id and key?

**Comment by SleepyBandit** [comment]
It may be something with you ID or KEY or how you pass them in code. Did you get this resolved? If not, how are you passing your credentials? It should look like the following with quotations around your ID and KEY values.
```
var config = {
    app_id : "YOUR_OXFORD_ACCOUNT_APP_ID",
    app_key : "YOUR_OXFORD_ACCOUNT_APP_KEY",
    source_lang : "en"
  };
```

**Comment by SleepyBandit** [comment]
Closing this since no response and I cannot replicate when using valid creds.
