### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by Ju01110101** [SleepyBandit/oxford-dictionary#9]
Using snippet provided, I'm getting this error:

Access to XMLHttpRequest at 'http://192.168.0.10:8080/sockjs-node/info?t=1573126923594' from origin 'http://localhost:8080' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Any idea how to solve that issue?

**Comment by SleepyBandit** [comment]
CORS issues are typically client side problems. It probably has to do with how you have implemented the solution.
